### ISSUE TITLE
While running the production jar I get WhitePage label error (404)

### ISSUE THREAD

**Issue by kaushalshah45-zz** [marco76/SpringAngular2TypeScript#1]

**Comment by marco76** [comment]
Hi,
did you started the application with `java -jar ./server-0.1.3-SNAPSHOT.war` in the target directory? The port of the server is 8082, the homepage is `http://localhost:8082`
Did spring boot generated the starting log?

**Comment by kaushalshah45-zz** [comment]
Yes Spring Boot is generating the starting log and it boots up successfully. But when I go to localhost:8082 I get the wjitepage label error

**Comment by kaushalshah45-zz** [comment]
Also when I go to http://localhost:8082/result_list I get a proper JSON response.

**Comment by marco76** [comment]
I fixed it. There was a problem in the frontend pom.xml. The frontend files were not deployed.
It should work correctly now with the new sources.
Thanks.
